---
- name: Manage packages
  hosts: all
  become: true
  tasks:
    - name: Install packages on Debian-based systems
      apt:
        name:
          - nmap
          - htop
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Remove packages on Debian-based systems
      apt:
        name:
          - apache2
        state: absent
      when: ansible_facts['os_family'] == "Debian"

    - name: Install packages on RedHat-based systems
      yum:
        name:
          - nmap
          - htop
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Remove packages on RedHat-based systems
      yum:
        name:
          - httpd
        state: absent
      when: ansible_facts['os_family'] == "RedHat"
