---
- name: Update package metadata for multiple distributions
  hosts: all
  become: true
  tasks:
    - name: Update package metadata on Debian-based systems
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Update package metadata on Red Hat-based systems (CentOS, RHEL, Oracle Linux)
      yum:
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Update package metadata on FreeBSD systems
      command: pkg update -f
      when: ansible_facts['os_family'] == "FreeBSD"
