---
- name: List installed kernels on each host
  hosts: all
  gather_facts: true
  vars:
    ansible_ssh_extra_args: "-o KexAlgorithms=+diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa -o MACs=hmac-sha1"
  tasks:
    - name: List kernels on Debian-based systems
      shell: dpkg -l | grep linux-image
      register: debian_kernels
      when: ansible_facts['os_family'] == "Debian"

    - name: Display installed kernels on Debian-based systems
      debug:
        msg: "{{ debian_kernels.stdout_lines }}"
      when: ansible_facts['os_family'] == "Debian"

    - name: List kernels on RedHat-based systems
      shell: rpm -q kernel
      register: redhat_kernels
      when: ansible_facts['os_family'] == "RedHat"

    - name: Display installed kernels on RedHat-based systems
      debug:
        msg: "{{ redhat_kernels.stdout_lines }}"
      when: ansible_facts['os_family'] == "RedHat"

    - name: List kernels on FreeBSD systems
      shell: ls /boot/kernel*
      register: freebsd_kernels
      when: ansible_facts['os_family'] == "FreeBSD"

    - name: Display installed kernels on FreeBSD systems
      debug:
        msg: "{{ freebsd_kernels.stdout_lines }}"
      when: ansible_facts['os_family'] == "FreeBSD"
