---
- name: Remove a user completely and leave "sistema" as the only admin
  hosts: all
  become: true
  vars:
    username_to_remove: bos
    admin_user: sistema
    admin_password: "{{ 'supersistema' | password_hash('sha512') }}"
  tasks:
    - name: Remove the user "{{ username_to_remove }}"
      user:
        name: "{{ username_to_remove }}"
        state: absent
        remove: true  # Remove home directory and mail spool

    - name: Ensure no files/directories owned by "{{ username_to_remove }}" remain
      find:
        paths: /
        recurse: yes
        owners: "{{ username_to_remove }}"
      register: user_files

    - name: Delete all remaining files/directories owned by "{{ username_to_remove }}"
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ user_files.files }}"
      when: user_files.matched > 0

    - name: Recreate or ensure the admin user "{{ admin_user }}" exists
      user:
        name: "{{ admin_user }}"
        password: "{{ admin_password }}"
        state: present
        shell: /bin/bash
        groups: "{{ 'sudo' if ansible_facts['os_family'] == 'Debian' else 'wheel' }}"
        append: true

    - name: Ensure sudo privileges for "{{ admin_user }}" on Debian-based systems
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure wheel privileges for "{{ admin_user }}" on RedHat-based systems
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "FreeBSD"

    - name: Verify that the home directory of "{{ admin_user }}" exists
      file:
        path: "/home/{{ admin_user }}"
        state: directory
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: "0700"
