---
- name: Install Nmap
  hosts: all
  gather_facts: false  # Disabling fact gathering to speed up the playbook execution
  become: true
  tasks:
    - name: Install nmap
      ansible.builtin.command:
        cmd: sudo apt install nmap -y

