---
- name: Install Nmap based on Linux distribution
  hosts: all
  become: true
  tasks:
    - name: Install Nmap on Debian-based systems
      apt:
        name: nmap
        state: present
      when: ansible_facts['os_family'] == "Debian"
