---
- name: Install Nmap on Debian-based systems
  hosts: debian_servers  # Define a host group for Debian-based systems
  become: true  # Use sudo for elevated privileges
  tasks:
    - name: Update the APT package cache
      apt:
        update_cache: yes

    - name: Install Nmap
      apt:
        name: nmap
        state: present
