---
- name: Update multiple Linux distributions
  hosts: all
  become: true
  tasks:
    - name: Update packages on Debian-based systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian"

    - name: Update packages on Red Hat-based systems
      yum:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Update packages on Oracle Linux
      yum:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "OracleLinux"

    - name: Update packages on CentOS
      yum:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "CentOS"

    - name: Update packages on FreeBSD
      command: pkg upgrade -y
      when: ansible_facts['os_family'] == "FreeBSD"
